export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";
export const LOG_OUT = "LOG_OUT";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_BLOODPRESSURE = "GET_BLOODPRESSURE";
export const LOADING = "LOADING";
export const ADD_EXAMINATION = "ADD_EXAMINATION";
export const EDIT_EXAMINATION = "EDIT_EXAMINATION";
export const GET_GLUCOSE = "GET_GLUCOSE";
export const GET_SURGERY = "GET_SURGERY";
export const GET_EXAMINATION = "GET_EXAMINATION";
export const GET_DETAIL_BLOODPRESSURE = "GET_DETAIL_BLOODPRESSURE";
//bloodPressure
